### ISSUE TITLE
ASM App TRANSFER returns ERR INVALID

### ISSUE THREAD

**Issue by THEJON78** [jacobly0/transfer#14]
I seem to have everything correct but the ")"??
i have my Asm(prgmTRANSFER) and when I select goto, it goes to ")".
It's unarchived and everything.

SPECS; Ti84+
OS 5.55

**Comment by adriweb** [comment]
If you are on OS 5.5 or later, you'll need to follow the steps on https://yvantt.github.io/arTIfiCE/

**Comment by THEJON78** [comment]
> If you are on OS 5.5 or later, you'll need to follow the steps on https://yvantt.github.io/arTIfiCE/

oh i do? thanks! i though that was just for ce

**Comment by adriweb** [comment]
Uh, it is for the CE only. If you have the 84+ (non-CE), it won't work obviously but also this program here will not work either, as it's made for the CE.

and you probably have 2.55, then, not 5.55...

**Comment by THEJON78** [comment]
> Uh, it is for the CE only. If you have the 84+ (non-CE), it won't work obviously but also this program here will not work either, as it's made for the CE.

Oh, okay. Thanks.

> and you probably have 2.55, then, not 5.55...

Oops! i __did__ mistype that. Sorry.
