### ISSUE TITLE
USB mass storage > mtp

### ISSUE THREAD

**Issue by reesericci** [jacobly0/transfer#4]
Is there any way to convert this project into using the much more widely accepted USB mass storage standard instead of MTP?

--reesericci

**Comment by jacobly0** [comment]
USB MSD just gives you access to a bunch of blocks of storage that you can write whatever filesystem you want to.  However, the calculator does not store things in a common filesystem format and does not have enough memory to remember an entire extra filesystem that it would have to parse itself and convert back to its own format.  Even if you were to do it anyway, there would be almost no overlap between that program and this one.

**Comment by reesericci** [comment]
Ah bummer
