### ISSUE TITLE
Compatibility with standalone releases of clibs

### ISSUE THREAD

**Issue by UInt2048** [jacobly0/transfer#6]
Could this program be made compatible with the standalone release of clibs (found at https://github.com/CE-Programming/libraries/releases/) so that even if additional files must be there for this program to work, the libraries could be the normal standalone releases for others?

If not, what's too different to prevent this compatibility?

Thank you for the great program!

**Comment by jacobly0** [comment]
This program depends on an unreleased library, and unreleased libraries depend on the latest unreleased linker.  Once the library it depends on is released, it will be included in the latest release of clibs.

**Comment by UInt2048** [comment]
That's unfortunate. Hopefully it can be released soon!

**Comment by jacobly0** [comment]
It will be released once all the functionality is actually implemented.
